URL_Reverse_Resolution/URL_Reverse_Resolution/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("main/", include("main.urls", namespace="homepage")),
]

URL_Reverse_Resolution/main/urls.py
from django.urls import path
from . import views

app_name = "homepage"
urlpatterns = [
    path("first_view", views.first_view, name="main_view"),
    path("second_view", views.second_view, name="sub_view"),
    path("view/<slug:text>", views.view_with_path_parameters, name="param_view"),
]

URL_Reverse_Resolution/main/views.py
from django.shortcuts import render
from django.utils.html import escape

def first_view(request):
    context = {'view_name':'Main_View'}
    return render(request,"main/main_template.html",context)

def second_view(request):
    context = {'view_name': 'Sub_View'}
    return render(request,"main/secondary_template.html",context)

def view_with_path_parameters(request,text):
    context = {'view_name': 'Param_View', 'text': escape(text)}
    return render(request,"main/third_template.html",context)

URL_Reverse_Resolution/main/templates/main/main_template.html
<html>

<head></head>

<body>
<h2>View Name : {{ view_name }} </h2>
<a href="{% url 'homepage:sub_view' %}">Go To Sub View</a>
</body>

</html>

URL_Reverse_Resolution/main/templates/main/secondary_template.html
<html>

<head></head>

<body>

<h2>View Name : {{ view_name }} </h2>
<a href="{% url 'homepage:main_view' %}">Go To Main View</a><br>
<a href="{% url 'homepage:param_view' 56 %}">Go To Param View</a>
</body>

</html>

URL_Reverse_Resolution/main/templates/main/third_template.html
<html>

<head></head>

<body>
<h2>View Name : {{ view_name }} </h2>
<a href="{% url 'homepage:main_view' %}">Go To Main View</a>
<h2>URL Path Parameter Value: {{ text }}</h2>
</body>

</html>